[profile.default]
src = "."
out = "out"
libs = ["../lib"]
solc = "0.8.19"

remappings = [
    "forge-std/=../lib/forge-std/src/"
]

[profile.zksync]
src = "."
out = "out"
libs = ["../lib"]
solc = "0.8.19"

[rpc_endpoints]
lens_testnet = "https://rpc.testnet.lens.xyz"
