name = "karaoke-pipeline"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Cron schedule: Every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# Environment variables (override in .dev.vars for local dev)
[vars]

# Production secrets (set via `wrangler secret put`)
# - NEON_DATABASE_URL
# - QUANSIC_SERVICE_URL (optional)
