[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

# ZKsync configuration for Lens Network deployment
[profile.zksync]
src = "src"
test = "test"
script = "script"
out = "zkout"
libs = ["lib"]
fallback_oz = true
mode = "3"
solc = "0.8.30"

[rpc_endpoints]
lens_testnet = "https://rpc.testnet.lens.xyz"
lens_mainnet = "https://rpc.lens.xyz"
base_sepolia = "https://sepolia.base.org"

[etherscan]
lens_testnet = { key = "${LENSSCAN_API_KEY}", url = "https://block-explorer.testnet.lens.xyz/api" }

# Compiler settings
[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true
orderLiterals = true
deduplicate = true
cse = true
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = "dhfoDgvulfnTUtnIf"
