[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
via_ir = true
optimizer = true
optimizer_runs = 1
evm_version = "shanghai"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# zkSync profile for Lens Chain deployment
[profile.zksync]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "shanghai"
zksolc = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Lens Chain configuration
[rpc_endpoints]
lens-mainnet = "https://rpc.lens.xyz"
lens-testnet = "https://rpc.testnet.lens.xyz"

# [etherscan]
# lens-mainnet = { key = "${LENS_EXPLORER_API_KEY}", url = "https://explorer.lens.xyz/api" }
# lens-testnet = { key = "${LENS_EXPLORER_API_KEY}", url = "https://explorer.testnet.lens.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options