name = "karaoke-school-sponsorship-api"
main = "src/index.ts"
compatibility_date = "2024-11-01"

# Cloudflare Workers configuration for Lens Protocol sponsorship API
# Handles transaction sponsorship, anti-spam checks, and PKP verification

[env.production]
name = "karaoke-school-sponsorship-api"
route = "api.karaoke-school.xyz/*"

[env.development]
name = "karaoke-school-sponsorship-api-dev"

# Environment variables (secrets managed via `wrangler secret put`)
# Run these commands to set secrets:
#   wrangler secret put DATABASE_URL
#   wrangler secret put PRIVATE_KEY
#   wrangler secret put LENS_AUTH_BEARER_TOKEN

# Public env vars (non-sensitive)
[vars]
LENS_APP_ADDRESS = "0x77fc7265c6a52E7A9dB1D887fB0F9A3d898Ae5a0"
LENS_CUSTOM_NAMESPACE = "0xA5882f62feDC936276ef2e7166723A04Ee12501B"
LENS_CHAIN_ID = "37111"
LENS_RPC_URL = "https://rpc.testnet.lens.xyz"
MAX_SPONSORED_TXS = "10"
MIN_BALANCE_WEI = "10000000000000000"  # 0.01 GRASS

# Rate limiting (optional, enable if needed)
# [[unsafe.bindings]]
# name = "RATE_LIMITER"
# type = "ratelimit"
# namespace_id = "your_namespace_id"
# simple = { limit = 100, period = 60 }
