[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[profile.default.etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
