---
version: "2.2"

services:
  quansic:
    image: t3333chn0000/quansic-service:v2.0.1  # Python hrequests with JWT auth
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - webdisplay
    env:
      - PORT=3000
      - HOST=0.0.0.0

      # Quansic credentials
      - QUANSIC_EMAIL=christianimogen@tiffincrane.com
      - QUANSIC_PASSWORD=Temporarypw710!

      # Session management
      - SESSION_DURATION_MS=86400000              # 24 hours (matches refresh_jwt expiry)

      # Account rotation settings
      - REQUESTS_PER_ACCOUNT=30                   # Rotate after N requests
      - ROTATION_INTERVAL_MS=1800000              # Or after 30 minutes (in ms)

      # hrequests browser configuration
      - HREQUESTS_BROWSER=firefox
      - HREQUESTS_HEADLESS=true
      - HREQUESTS_TIMEOUT=30000

      # CORS and logging
      - ALLOWED_ORIGINS=*
      - LOG_LEVEL=INFO

profiles:
  compute:
    quansic:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 20Gi
            # Ephemeral storage for browser cache

  placement:
    akash:
      pricing:
        quansic:
          denom: uakt
          amount: 10000  # Max bid per block (~$0.01-0.03/hour)

deployment:
  quansic:
    akash:
      profile: quansic
      count: 1
