---
version: "2.2"

services:
  quansic:
    image: t3333chn0000/quansic-service:v1.1  # Updated with Spotify ID fallback for artist enrichment
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - webdisplay
    env:
      - PORT=3000
      - NODE_ENV=production
      - QUANSIC_EMAIL=
      - QUANSIC_PASSWORD=

profiles:
  compute:
    quansic:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 20Gi
            # Ephemeral storage for browser cache

  placement:
    akash:
      pricing:
        quansic:
          denom: uakt
          amount: 10000  # Max bid per block (~$0.01-0.03/hour)

deployment:
  quansic:
    akash:
      profile: quansic
      count: 1
