name = "tiktok-scraper"
main = "src/index.ts"
compatibility_date = "2024-11-01"

# Environment variables (set via: wrangler secret put NEON_DATABASE_URL)
# Secrets stored securely in Cloudflare, not in this file

[vars]
MODAL_FFMPEG_ENDPOINT = "http://395n0uo55tbfd885ch3mjn4dcs.ingress.octanecomputing.freeddns.org"

# Multiple Cron Triggers - Specialized enrichment pipelines
# Each cron runs independently with optimal frequency for its role
[triggers]
crons = [
  "*/3 * * * *",   # ISWC Discovery (high priority - BMI/CISAC/MusicBrainz/Quansic/MLC)
  "*/5 * * * *",   # Spotify Enrichment (tracks + artists)
  "*/10 * * * *",  # Genius Enrichment (songs + artists + referents)
  "*/12 * * * *",  # MusicBrainz Enrichment (artists) - changed from 15 to avoid conflict
  "*/20 * * * *",  # Quansic Enrichment (artists + works)
  "*/30 * * * *",  # Licensing Enrichment (MLC + BMI corroboration)
  "*/31 * * * *",  # CISAC IPI Discovery (every 31 minutes - catalog vacuum)
  "*/15 * * * *",  # Lyrics Enrichment (multi-source + AI)
  "*/25 * * * *",  # Audio Download (Freyr + Grove + AcoustID) - changed from 30 to avoid overlap
  "*/35 * * * *",  # Demucs Separation (Modal GPU vocal/instrumental separation)
  "*/40 * * * *",  # ElevenLabs Word Alignment (forced alignment for karaoke)
  "*/45 * * * *",  # Segment Selection (Gemini Flash - iconic 190s for tracks >190s)
  "*/50 * * * *",  # FFmpeg Crop (crop instrumental segments for fal.ai)
]
