name = "tiktok-scraper"
main = "src/index.ts"
compatibility_date = "2024-11-01"

# Environment variables (set via: wrangler secret put NEON_DATABASE_URL)
# Secrets stored securely in Cloudflare, not in this file

# Cron trigger - Run enrichment pipeline every 5 minutes
[triggers]
crons = ["*/5 * * * *"]
