---
version: "2.2"

services:
  cisac:
    image: t3333chn0000/cisac-service:v1.0.1
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - webdisplay
    env:
      - PORT=3000
      - NODE_ENV=production
      - TWOCAPTCHA_API_KEY=your_api_key_here  # ← Replace with your 2captcha API key

profiles:
  compute:
    cisac:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 20Gi
            # Ephemeral storage for browser cache

  placement:
    akash:
      pricing:
        cisac:
          denom: uakt
          amount: 10000  # Max bid per block (~$0.01-0.03/hour)

deployment:
  cisac:
    akash:
      profile: cisac
      count: 1
