version: "2.2"

services:
  demucs-cpu:
    image: t3333chn0000/demucs-cpu@sha256:414db1161424570743193712d0d0fe84d22eb7e781df225f93004155d1508b1c
    expose:
      - port: 8002
        as: 80
        to:
          - global: true
    env:
      # Service configuration
      - PORT=8002
      - HOST=0.0.0.0

      # Demucs CPU-specific configuration
      - DEMUCS_MODEL=mdx_q  # CPU-optimized quantized model
      - SEPARATION_TIMEOUT=600  # 10 minutes max for CPU processing

      # Grove IPFS configuration
      - GROVE_CHAIN_ID=37111  # Base Sepolia testnet

      # Neon Database configuration (set via environment secrets in Akash)
      # - NEON_DATABASE_URL=postgresql://... (provided via Akash secrets)

profiles:
  compute:
    demucs-cpu:
      resources:
        cpu:
          units: 2  # 2 CPU cores for sequential processing
        memory:
          size: 4Gi  # 4GB RAM for MDX models and audio processing
        storage:
          - size: 10Gi  # 10GB for models, temp files, audio processing

  placement:
    akash:
      pricing:
        demucs-cpu:
          denom: uakt
          amount: 30000  # ~$0.03-0.07/hour for CPU service

deployment:
  demucs-cpu:
    akash:
      profile: demucs-cpu
      count: 1
